#!/usr/bin/bash

BASE=`dirname $0`
ABS_BASE=`cd $BASE && pwd`
WORKING=`pwd`
OUTDIR=${3:-$ABS_BASE}

wget ${1:-http://github.com/apache/qpid-dispatch/archive/master.tar.gz} -O qpid-dispatch.tar.gz
wget ${2:-https://dist.apache.org/repos/dist/dev/qpid/proton/0.22.0-rc1/qpid-proton-0.22.0.tar.gz} -O qpid-proton.tar.gz

mkdir qpid-dispatch-src qpid-proton-src build staging proton_build proton_install
tar -zxf qpid-dispatch.tar.gz -C qpid-dispatch-src --strip-components 1
tar -zxf qpid-proton.tar.gz -C qpid-proton-src --strip-components 1
if [ -f "$PATCH_FILE" ]; then
    echo "patching with $PATCH_FILE"
    patch -d qpid-dispatch-src -p1 < "$PATCH_FILE"
fi;

cd proton_build
cmake -DCMAKE_INSTALL_PREFIX=$WORKING/proton_install -DBUILD_CPP=OFF -DBUILD_PERL=OFF -DBUILD_RUBY=OFF -DBUILD_JAVA=OFF -DBUILD_GO=OFF -DBUILD_JAVASCRIPT=OFF -DBUILD_PHP=OFF $WORKING/qpid-proton-src/ && make && make install
cd $WORKING/build
CMAKE_PREFIX_PATH=$WORKING/proton_install cmake -DBUILD_DOCS=OFF -DCONSOLE_INSTALL=OFF -DCMAKE_INSTALL_PREFIX=/usr $WORKING/qpid-dispatch-src/ && make && make DESTDIR=$WORKING/staging/ install && tar -z -C $WORKING/staging/ -cf $OUTDIR/qpid-dispatch-binary.tar.gz usr etc
